substitutions:
  name: "trampletek blue"
  friendly_name: "TrampleTek Mat"

dashboard_import:
  package_import_url: github://ascking9/TrampleTek-Blue-code/TrampleTek_bootup.yaml@main
  import_full_config: false

packages:
  device_base: !include TrampleTek_Debug/TrampleTek_ESPHome_bootup.yaml