substitutions:
  name: "trampletek blue"
  friendly_name: "TrampleTek Mat"

dashboard_import:
  package_import_url: github://everythingsmarthome/everything-presence-one/everything-presence-one.yaml@main
  import_full_config: false

packages:
  device_base: !include common/everything-presence-one-base.yaml